### ISSUE TITLE
Index out of bound error

### ISSUE THREAD

**Issue by akshat-v** [JojiJoseph/RGBD-to-Anaglyph#1]
While trying to run the code for my own images which are resized to the same size as car.jpg , I get an index out of bound error. The error is as follows

`Generating right eye view...
  2%|█▎                                                                               | 8/480 [00:00<00:04, 102.41it/s]
Traceback (most recent call last):
  File "rgbd_to_anaglyph.py", line 113, in <module>
    img_right, mask = construct_right_image(img_left, img_depth, params)
  File "rgbd_to_anaglyph.py", line 37, in construct_right_image
    img_right[y_, x_] = img_left[y,x]
IndexError: index -1392 is out of bounds for axis 1 with size 640`

**Comment by JojiJoseph** [comment]
Hi Akshat, Thanks for raising this issue.

There was a bug in which the interpolated coordinates (x_, y_) of the right image corresponding to (x, y) of the left image could be outside of the image.

I have fixed it and updated this repo. Could you please check if the problem is resolved?

**Comment by akshat-v** [comment]
Thanks for the prompt response. Seems to work now.
