### ISSUE TITLE
Format of the depth image

### ISSUE THREAD

**Issue by akshat-v** [JojiJoseph/RGBD-to-Anaglyph#2]
Can you please tell what are the specifications for the type of depth image required? 
I am trying to work with maps where I have the RGB image of a map and a depth image which contains the depth values of the corresponding pixels in meters.
I would have to convert my depth image to the format which is accepted in the model to get results as the current results are nonsensical.

**Comment by JojiJoseph** [comment]
The size of the depth image should be that of RGB image. They both must be aligned and ideally shouldn't have any distortion. The default unit of depth is mm. But you can change it by using the command line argument `--normalization-factor` or `-nf` (Please pull the latest update). As your depth is in meters, you can use 1 as normalization factor. 

For example you can type,
```bash
python rgbd_to_anaglyph.py -i <your_rgb_image> -d <your_depth_image> -nf 1 -opt
```
Other default values you may need to change are  as follows,

focal length = 525 pix
distance between (eyes) left and right image sensors = 0.05 m (5 cm)
optical center (cx, cy) = (319.5, 239.5)

These can be modified using the [command line arguments](https://github.com/JojiJoseph/RGBD-to-Anaglyph#usage).

**Comment by akshat-v** [comment]
Thank you for your reply. Is the depth image supposed to be 16-bit?

**Comment by JojiJoseph** [comment]
If the value of depth doesn't exceed 255, you can use 8-bit also.

**Comment by akshat-v** [comment]
-nf doesn't seem to be working, says unrecognized arguments

**Comment by JojiJoseph** [comment]
Could you please verify if you are using the latest update? If so, can you please post the screenshot of the error message?

**Comment by akshat-v** [comment]
Seems to work now. Thanks a lot!
