### ISSUE TITLE
Error after optimization step

### ISSUE THREAD

**Issue by akshat-v** [JojiJoseph/RGBD-to-Anaglyph#3]
```
Traceback (most recent call last):
  File "rgbd_to_anaglyph.py", line 130, in <module>
    img_sbs = np.concatenate([img_left, img_right], axis=1)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 3 dimension(s)
```
Getting this error after the image is created and optimized. Using the same images that I had used before and was successful in creating the 3D image.  Have the latest version of the code

**Comment by JojiJoseph** [comment]
It seems img_left (=the input rgb image) is a grayscale image. Could you please check if you have reversed the order of images while specifying them in the command line?

**Comment by akshat-v** [comment]
Hi, I am trying to convert an image to 3D but the result I am not getting is not that great for me. I want the object depths to be exaggerated more (I have a cliff-like structure at the center of the image) but multiplying the values in the depth image doesn't help (because it just makes all objects equally farther). Do you have any solutions to exaggerate the output so that the height of the cliff looks higher?

**Comment by JojiJoseph** [comment]
Can you try increasing the focal length (-f)? Are you giving the actual focal length of the camera to the script? Also, resizing the images isn't necessary if you provide the camera's actual f, cx and cy.

If you post links to some sample images, I will take a look at them.

**Comment by akshat-v** [comment]
So basically I have a satellite image of a mountain range and I want to make it so that I can get it in 3D to demonstrate the difference in the height of the hill range and the surrounding.
I also have its corresponding DEM file (which I am using as a proxy for the depth file) which contains the elevation of each pixel in meters.

Till now what I was doing was making a few changes to the DEM file which converted it to values similar to those of a depth file (ranging from 100-400 cm) for the image and then running the code using the default focal length. The output anaglyph image is 3D and I can see the difference, but it is very small. I want the height difference of the hills to be exaggerated.

**Comment by JojiJoseph** [comment]
If DEM file contains height, I guess you might have converted it to distance from the camera by subtracting from a constant number (It would be better if this constant is the distance to the satellite from the sea level).

I guess, you did the following calculation.

depth = distance to the satellite from sea level - the elevation of the hill from the sea level.

And exaggerated depth as,

new_depth = distance to the satellite from sea level - k * (the elevation of the hill from the sea level).

If you followed the same equations, I don't know what can be done to exaggerate the heights. If you have used the elevation as depth, can you try the above equations?

**Comment by akshat-v** [comment]
I have done the above equations that you mentioned previously. I think the issue might be not having the value of the focal length. I can see the exaggeration changing when I change the focal length, but many times it leads to the red and blue image not converging when viewed through the glass and the output doesn't just work out. Is there any solution to that?

**Comment by JojiJoseph** [comment]
I'm not able to think of any solution. But I will update you if I come across a solution.
